export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="swift"
plugins=(git git-flow github pip svn emacs-mode osx mvn vagrant node npm grails brew history-substring-search cake sublime autojump dircycle lein zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# python
# virtualenvwrapper
#export WORKON_HOME=$HOME/.virtualenvs
#export PIP_VIRTUALENV_BASE=$WORKON_HOME
#export PIP_RESPECT_VIRTUALENV=true
#source /usr/local/bin/virtualenvwrapper.sh

# ruby
# rvm
[[ -s "/Users/$USER/.rvm/scripts/rvm" ]] && source "/Users/$USER/.rvm/scripts/rvm" 

# python
# pythonbrew
[[ -s $HOME/.pythonbrew/etc/bashrc ]] && source $HOME/.pythonbrew/etc/bashrc

PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"

#autojump
[[ -f `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
